"""Execution-layer error leaves. v1.0 PR-D — ExecutionError category.

The two carrier leaves (:class:`LLMBehaviorError`,
:class:`ToolError`) live in their topic modules (``activegraph/llm/errors.py``
and ``activegraph/tools/errors.py``) because the per-reason prose
tables are co-located with the modules that raise them. This module
holds the runtime-internal execution-layer leaves that don't fit
cleanly into either topic.

PR-D adds:

- :class:`ApprovalNotFoundError` — pending-approval lookup miss.
  Fires from ``runtime.approve(approval_id)`` when the id doesn't
  refer to any pending approval. Multi-inherits :class:`LookupError`
  for back-compat with user code catching the builtin around the
  approval API.
"""

from __future__ import annotations

from typing import Any, Optional

from activegraph.errors import ExecutionError


class ApprovalNotFoundError(ExecutionError, LookupError):
    """Pending-approval lookup miss.

    Fires from ``runtime.approve(approval_id)`` when the id doesn't
    refer to any currently-pending approval. Multi-inherits
    :class:`LookupError` so user code that does ``except LookupError``
    around the approval API continues to work.
    """

    _doc_slug = "approval-not-found-error"

    def __init__(
        self,
        approval_id: str,
        *,
        pending_count: Optional[int] = None,
    ) -> None:
        self.approval_id = approval_id
        self.pending_count = pending_count
        ctx: dict[str, Any] = {"approval_id": approval_id}
        if pending_count is not None:
            ctx["pending_count"] = pending_count
        pending_hint = (
            f"There are currently {pending_count} pending approvals; "
            f"none of them match {approval_id!r}."
            if pending_count is not None
            else "There are no pending approvals in this runtime."
        )
        ExecutionError.__init__(
            self,
            f"no pending approval named {approval_id!r}",
            what_failed=(
                f"runtime.approve({approval_id!r}) could not find a pending "
                f"approval with that id.\n  {pending_hint}"
            ),
            why=(
                "Approval ids are generated by the runtime when a behavior "
                "calls ctx.propose_object under a gating policy "
                "(memo_approval, risk_approval, etc.). Each id is unique "
                "to its runtime instance and is consumed when approve() "
                "succeeds. A miss means either the id is stale (already "
                "approved or denied), the runtime instance is fresh "
                "(approvals don't carry across Runtime.load), or the id is "
                "a typo. The framework refuses to no-op an unknown id "
                "because that would silently corrupt the approval audit "
                "trail."
            ),
            how_to_fix=(
                "List the currently-pending approvals:\n"
                "    rt.pending_approvals()\n"
                "to confirm what's actually pending. The diligence demo's\n"
                "step_2_approval_demo (examples/diligence_real_run.py)\n"
                "shows the canonical pattern: enumerate, then approve by id."
            ),
            context=ctx,
        )
