"""Walk the public surface (`__all__` of `activegraph` and pack-level
`__all__`s) and produce a coverage report against the CONTRACT v1.0
#C2 tier model: 100% on public surface, 80% on the second ring.

Output: ``docs/reference/api/COVERAGE_REPORT.md``. The docstring-gate
commit consumes this as a checklist.

Classification per symbol:

- **full** — at least 3 lines of substantive prose, or has obvious
  structured sections (Args:, Returns:, Raises:, Examples:).
- **one-line** — single-line docstring; renders but is thin.
- **missing** — no docstring at all.

Tier:

- **public** — symbol in `activegraph.__all__` or a pack's top-level
  `__all__`. Target: 100% full or one-line; aim for full.
- **second** — module reachable via `import activegraph.X` but the
  symbol isn't in any `__all__`. Target: 80%.
- **internal** — symbols beginning with underscore, or modules not
  reachable as documented imports. Not gated.

Re-run after every batch of docstring fixes to confirm the report
shrinks.
"""

from __future__ import annotations

import inspect
import pkgutil
import sys
from collections import defaultdict
from pathlib import Path

import activegraph


REPO_ROOT = Path(__file__).resolve().parent.parent
REPORT_PATH = REPO_ROOT / "docs" / "reference" / "api" / "COVERAGE_REPORT.md"


def classify(obj) -> str:
    """Classify a symbol's docstring as full / one-line / missing."""
    doc = inspect.getdoc(obj)
    if not doc:
        return "missing"
    nonblank = [line for line in doc.strip().split("\n") if line.strip()]
    if len(nonblank) <= 1:
        return "one-line"
    if any(s in doc for s in ("Args:", "Returns:", "Raises:", "Examples:", "Example:")):
        return "full"
    if len(nonblank) >= 3:
        return "full"
    return "one-line"


def walk_public_surface() -> dict[str, list[tuple[str, str]]]:
    """Return mapping of module path -> [(symbol_name, classification)]."""
    result: dict[str, list[tuple[str, str]]] = defaultdict(list)
    seen: set[int] = set()

    # activegraph.__all__
    for name in activegraph.__all__:
        obj = getattr(activegraph, name, None)
        if obj is None:
            result["activegraph"].append((name, "missing"))
            continue
        if id(obj) in seen:
            continue
        seen.add(id(obj))
        result["activegraph"].append((name, classify(obj)))

    # Pack-level __all__s
    pack_module_names = []
    if hasattr(activegraph, "packs"):
        for finder, modname, ispkg in pkgutil.iter_modules(
            activegraph.packs.__path__, "activegraph.packs."
        ):
            if ispkg:
                pack_module_names.append(modname)

    for modname in pack_module_names:
        try:
            mod = __import__(modname, fromlist=["pack"])
        except Exception:
            continue
        all_list = getattr(mod, "__all__", None)
        if not all_list:
            continue
        for name in all_list:
            obj = getattr(mod, name, None)
            if obj is None:
                result[modname].append((name, "missing"))
                continue
            if id(obj) in seen:
                continue
            seen.add(id(obj))
            result[modname].append((name, classify(obj)))

    return result


def format_report(surface: dict[str, list[tuple[str, str]]]) -> str:
    lines: list[str] = []
    lines.append("# Docstring coverage report — public surface")
    lines.append("")
    lines.append(
        "Auto-generated by ``scripts/audit_docstrings.py``. The docstring-gate "
        "commit consumes this as a checklist.\n"
    )
    lines.append(
        "Tier model from CONTRACT v1.0 #C2: 100% on the explicit public surface "
        "(symbols in `__all__`), 80% on the second ring (importable but not "
        "re-exported), no gate on internals.\n"
    )
    lines.append(
        "Classification: ``full`` (≥3 lines OR has Args/Returns/Raises/Examples), "
        "``one-line`` (single line; renders but thin), ``missing`` (no docstring).\n"
    )

    total = 0
    full = 0
    for modname in sorted(surface):
        entries = surface[modname]
        if not entries:
            continue
        lines.append("")
        lines.append(f"## {modname} (public surface, target 100%)")
        lines.append("")
        for name, status in sorted(entries):
            mark = "x" if status == "full" else " "
            note = "" if status == "full" else f" — **{status}**"
            lines.append(f"- [{mark}] `{name}`{note}")
            total += 1
            if status == "full":
                full += 1

    # Summary
    pct = (full / total * 100) if total else 100.0
    gap = total - full
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"Public surface: **{full}/{total} fully documented "
                 f"({pct:.1f}%)** — gap to 100% target: **{gap} symbols**.")
    lines.append("")
    if gap > 0:
        lines.append(
            f"v1.0-rc1 readiness note: at {pct:.1f}% coverage, the doc site "
            f"renders but the gap is operator-visible. The docstring-gate "
            f"commit walks this checklist and fixes the unchecked items "
            f"before rc1 ships."
        )
    else:
        lines.append("All public-surface symbols are fully documented.")
    return "\n".join(lines) + "\n"


def main() -> int:
    surface = walk_public_surface()
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(format_report(surface))
    print(f"wrote {REPORT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
